const MovieData = [{
  Id: Math.random(),
    Title: 'Star Wars:A New Hope',
    Description :'With the planet-destroying power of the Death Star, the Empire looks to cement its grip on the galaxy. Meanwhile, farm boy Luke Skywalker rises to face his destiny.',
    IMDBRating: 4,
    Type: 'movie',
    Rate: '****',
    Trailer:'https://youtu.be/Q0CbN8sfihY',
    Poster: 'https://cdna.artstation.com/p/assets/images/images/028/452/966/large/visyrion-art-4-new-hope.jpg?1594527010',
    },
  
  {
    Id: Math.random(),
    Title: 'Star Wars:The Rise of Kkywalker',
    IMDBRating: 5,
    Description:'A powerful enemy returns and Rey must face her destiny.',
    Type: 'movie',
    Rate: '*****',
    Trailer:'https://youtu.be/Q0CbN8sfihY',
    Poster: 'https://lecahier.com/wp-content/uploads/2019/12/star-wars-the-rise-of-skywalker-theatrical-poster-1000_ebc74357.jpeg'
  },
  {Id: Math.random(),
    Title: 'Star Wars:The Last Jedi',
    Description:'Rey has found the legendary Luke Skywalker, hoping to be trained in the ways of the Force. Meanwhile, the First Order seeks to destroy the remnants of the Resistance and rule the galaxy unopposed.',
    IMDBRating: 2,
    Type: 'movie',
    Rate: '**',
    Trailer:'https://youtu.be/Q0CbN8sfihY',
    Poster: 'https://lumiere-a.akamaihd.net/v1/images/the-last-jedi-theatrical-poster-film-page_bca06283.jpeg?region=0%2C0%2C480%2C711'
  },
  {Id: Math.random(),
    Title: 'Star Wars:Return of Jedi',
    Description:'Luke Skywalker leads a mission to rescue his friend Han Solo from the clutches of Jabba the Hutt, while the Emperor seeks to destroy the Rebellion once and for all with a second dreaded Death Star.',
    IMDBRating: 3,
    Type: 'movie',
    Rate: '***',
    Trailer:'https://youtu.be/Q0CbN8sfihY',
    Poster: 'https://lumiere-a.akamaihd.net/v1/images/Star-Wars-Return-Jedi-VI-Poster_a10501d2.jpeg?region=12%2C9%2C618%2C982&width=480'
  },
  {Id: Math.random(),
    Title: 'Star Wars:The Force Awakens',
    Description:'Thirty years after the Battle of Endor, a new threat has risen in the form of the First Order and the villainous Kylo Ren. Meanwhile, Rey, a young scavenger, discovers powers that will change her life -- and possibly save the galaxy.',
    IMDBRating: 4,
    Type: 'movie',
    Rate: '****',
    Trailer:'https://youtu.be/Q0CbN8sfihY',
    Poster: 'https://starwarsblog.starwars.com/wp-content/uploads/2015/10/star-wars-force-awakens-official-poster-691x1024.jpg'
  },
  {Id: Math.random(),
    Title: 'Disney:Change For Your Man',
    Description:'Ariel gives up her voice so she can try to win over the man of her dreams, and the little mermaid eventually decides to become a human permanently so she can marry him.',
    IMDBRating: 1,
    Type: 'movie',
    Rate: '*',
    Trailer:'https://youtu.be/Q0CbN8sfihY',
  Poster: 'https://laughingsquid.com/wp-content/uploads/2013/06/LittleMermaid.jpg'
},
{Id: Math.random(),
  Title: 'Disney:Aladdin',
  Description:'In a mythical city, street-smart Aladdin and Princess Jasmine join forces to save the kingdom from the evil sorcerer Jafar! Along the way, Aladdin learns to believe in himself with help from a hilarious Genie and three wishes that change everything!',
  IMDBRating: 1,
  Type: 'movie',
  Rate: '*',
  Trailer:'https://youtu.be/Q0CbN8sfihY',
Poster: 'https://lumiere-a.akamaihd.net/v1/images/p_aladdin1992_20486_174ba005.jpeg'
},
]

export default MovieData
